apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kanboard
  name: ejemplo1-kanboard
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kanboard
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kanboard
    spec:
      containers:
      - image: kanboard/kanboard:v1.2.44
        name: kanboard
        resources: {}
status: {}
