apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: kanboard
  name: ejemplo1-kanboard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: kanboard
status:
  loadBalancer: {}
